### ISSUE TITLE
Code Compile Error

### ISSUE THREAD

**Issue by Rahulgupta-cdnsol** [fullstackio/FlappySwift#61]
Hi,

I have downloaded the code and try to compile on XCode 6.4 and gets compilation error.

**Comment by markwarnertapjoy** [comment]
I have also tried to compile with xcode 7.1 and get the following compile errors.
Users/fred.user/Downloads/samples/ios/ios-sdk-demo-flappy-master/FlappyBird/GameScene.swift:208:19:
Method does not override any method from its superclass



/Users/fred.user/Downloads/samples/ios/ios-sdk-demo-flappy-master/FlappyBird/GameScene.swift:127:13:
Variable 'ground' was never mutated; consider changing to 'let' constant



/Users/fred.user/Downloads/samples/ios/ios-sdk-demo-flappy-master/FlappyBird/GameScene.swift:173:13:
Variable 'contactNode' was never mutated; consider changing to 'let' constant



/Users/fred.user/Downloads/samples/ios/ios-sdk-demo-flappy-master/FlappyBird/GameScene.swift:212:21:
Initialization of immutable value 'location' was never used; consider replacing
with assignment to '_' or removing it



/Users/fred.user/Downloads/samples/ios/ios-sdk-demo-flappy-master/FlappyBird/GameScene.swift:259:85:
'AnyObject!' is not convertible to 'TJPlacement'; did you mean to use 'as!' to
force downcast?



/Users/fred.user/Downloads/samples/ios/ios-sdk-demo-flappy-master/FlappyBird/GameViewController.swift



/Users/fred.user/Downloads/samples/ios/ios-sdk-demo-flappy-master/FlappyBird/GameViewController.swift:69:19:
Method does not override any method from its superclass



/Users/fred.user/Downloads/samples/ios/ios-sdk-demo-flappy-master/FlappyBird/GameViewController.swift:15:58:
'NSString' is not implicitly convertible to 'String'; did you mean to use 'as'
to explicitly convert?



/Users/fred.user/Downloads/samples/ios/ios-sdk-demo-flappy-master/FlappyBird/GameViewController.swift:51:36:
'UIView!' is not convertible to 'SKView'; did you mean to use 'as!' to force
downcast?



/Users/fred.user/Downloads/samples/ios/ios-sdk-demo-flappy-master/FlappyBird/AppDelegate.swift



/Users/fred.user/Downloads/samples/ios/ios-sdk-demo-flappy-master/FlappyBird/AppDelegate.swift:24:10:
Objective-C method 'application:didFinishLaunchingWithOptions:' provided by
method 'application(_:didFinishLaunchingWithOptions:)' conflicts with optional
requirement method 'application(_:didFinishLaunchingWithOptions:)' in protocol
'UIApplicationDelegate'

**Comment by pawurb** [comment]
Already resolved on master, closing.
